### ISSUE TITLE
Igdb::Game.search ArgumentError: wrong number of arguments

### ISSUE THREAD

**Issue by bitangxxx** [tastycake/igdb_api#1]
Hi,

I've just tried a simple search based on gem documentation with this call:
`Igdb::Game.search(query: 'batman')`

and it raised an error:

> ArgumentError: wrong number of arguments (1 for 2)
	from /Users/csikszem/work/rukkola/config/initializers/ruby_extensions.rb:4:in `reduce'
	from /Users/csikszem/work/rukkola/vendor/ruby/2.1.0/gems/igdb_api-0.8.0/lib/igdb/models/api_resource.rb:42:in `build_collection'
	from /Users/csikszem/work/rukkola/vendor/ruby/2.1.0/gems/igdb_api-0.8.0/lib/igdb/models/api_resource.rb:24:in `search'
	from (irb):16
	from /Users/csikszem/work/rukkola/vendor/ruby/2.1.0/gems/railties-3.2.13/lib/rails/commands/console.rb:47:in `start'
	from /Users/csikszem/work/rukkola/vendor/ruby/2.1.0/gems/railties-3.2.13/lib/rails/commands/console.rb:8:in `start'
	from /Users/csikszem/work/rukkola/vendor/ruby/2.1.0/gems/railties-3.2.13/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>

Could you help me investigate this issue?
Thanks!

**Comment by bitangxxx** [comment]
my bad, sorry
